version: '3.7'
networks:
  selenoid:
    external:
      name: selenoid
services:
  selenoid:
    networks:
      - selenoid
    image: aerokube/selenoid:latest
    # network_mode: host
    container_name: selenoid
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/var/selenoid/video
      - OVERRIDE_VNC_PASSWORD=secret
      - OVERRIDE_SELENIUM_HUB_PORT=4444
      - OVERRIDE_SELENIUM_NODE_PORT=5555
      - OVERRIDE_SELENOID_PORT=4444
      - OVERRIDE_SELENOID_VERSION=3.141.59
      - MAX_INSTANCES=10
      - MAX_SESSIONS=10
      #- SELENOID_OPTS=-logLevel=verbose
      - SELENOID_CONFIGURATION_PATH=/etc/selenoid/browsers.json
      #- SELENOID_LIMITS=20
      #- VERBOSE=true
      - SELENOID_LOG=wd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /var/selenoid:/var/selenoid
      - /etc/selenoid:/etc/selenoid
     # - ./logs:/opt/selenoid/logs
      - ./browsers.json:/etc/selenoid/browsers.json
    command: ["-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "50", "-timeout", "10m", "-mem", "2g", "-cpu", "1.5", "-container-network", "selenoid", "-session-attempt-timeout", "3m"]
    ports:
      - "4444:4444"
  selenoid-ui:
    networks:
      - selenoid
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    # network_mode: host
    links:
      - selenoid
    environment:
      - API_URL=http://selenoid:4444
      - SELENOID_UI_PORT=8180
      #- SELENIUM_HUB_PORT_4444_TCP_ADDR=selenoid
      #- SELENIUM_HUB_PORT_4444_TCP_PORT=4444
      #- SELENOID_UI_CONFIG_DIR=/etc/selenoid
    volumes:
          - /etc/localtime:/etc/localtime:ro
    ports:
      - 8081:8080
    command: ["--selenoid-uri","http://selenoid:4444"]
